### ISSUE TITLE
Twitter Share on Safari

### ISSUE THREAD

**Issue by miguelmoraleda** [vweevers/share-dialog#1]
Hi @vweevers,

I having problems with the twitter dialog on Safari. FB and Google+ are working perfectly, but the Twitter dialog is never appearing for me.

Any suggestion? Ideas?

Thanks in advance.

Best regards,

Miguel

**Comment by vweevers** [comment]
That reminds me, I should add cross browser tests to this module. For this specific issue however, I need some more information, because I can't seem to replicate it.
- Which versions of Safari have you tested?
- Does Safari's Web Inspector show any error?

A copy/paste of your code is helpful too.

**Comment by miguelmoraleda** [comment]
Safari: Version 8.0.2 (10600.2.5)

OSX Yosemite: 10.10.1 (14B25)

No errors on Web Inspector..

FB and GooglePlus are working fine

**Comment by miguelmoraleda** [comment]
I will let you know if I find what is going on

**Comment by miguelmoraleda** [comment]
Hey @vweevers,

I found the solution for my error. Safari is preventing `window.open` to work outside of an onClick function. So, that's why it wasn't working. Maybe you could add a note/warning about it on the Readme.

Best regards,

Miguel

**Comment by vweevers** [comment]
Ah, okay. Thanks for your feedback.
