### ISSUE TITLE
Callback for dialogs

### ISSUE THREAD

**Issue by miguelmoraleda** [vweevers/share-dialog#2]
Hey @vweevers,

Is there a way to detect if the user shared for real ? I mean, is it possible to detect if the user shared or closed the dialog?

Thanks in advance.

Best regards,

Miguel

**Comment by vweevers** [comment]
No, I'm afraid not. For Facebook maybe, but then you'd have to use Open Graph and require the user to login.

**Comment by vweevers** [comment]
What you can get are total number of shares, using something like the [SharedCount](http://www.sharedcount.com/) API. But not per-user.
